jobs:
  - script: >
      job('Seed All DSL jobs') {
        description('Seed job for all DSL jobs')
        scm {
            git {
                remote { 
                    url "https://github.com/ppalit/jenkins-ec2-ecs.git"
                }
                branch '*/main'
                extensions {
                  cleanAfterCheckout()
                  wipeOutWorkspace()
                }
              }
        }
        triggers {
            scm('H/15 * * * *')
        }
        steps {
          dsl {
            external('${JENKINS_JOB_DSL_PATH:-jobs}/*.groovy')
            removeAction('DELETE')
          }
        }
      }
